# Generated by Django 5.1 on 2024-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="date",
            field=models.CharField(max_length=255),
        ),
    ]
